### ISSUE TITLE
500: INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by musicformellons** [23andMe/djdt-flamegraph#1]
I get the Flamegraph tab in the Toolbar, but I get a: 500: INTERNAL SERVER ERROR

Details:
Traceback (most recent call last):
  File "/home/usr/.pyenv/versions/pq/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/home/usr/.pyenv/versions/3.4.3/lib/python3.4/contextlib.py", line 30, in inner
    return func(_args, *_kwds)
  File "/home/usr/.pyenv/versions/pq/lib/python3.4/site-packages/debug_toolbar/views.py", line 19, in render_panel
    content = panel.content
  File "/home/usr/.pyenv/versions/pq/lib/python3.4/site-packages/djdt_flamegraph/djdt_flamegraph.py", line 55, in content
    'flamegraph': flamegraph.stats_to_svg(self.sampler.get_stats())
  File "/home/usr/.pyenv/versions/pq/lib/python3.4/site-packages/djdt_flamegraph/flamegraph.py", line 15, in stats_to_svg
    out, _ = proc.communicate(stats)
  File "/home/usr/.pyenv/versions/3.4.3/lib/python3.4/subprocess.py", line 960, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/home/usr/.pyenv/versions/3.4.3/lib/python3.4/subprocess.py", line 1602, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: str object does not have the buffer interface

**Comment by blopker** [comment]
Thank you for the report. Python 3 wasn't tested very well, but now it is. New release is on PyPI.

**Comment by musicformellons** [comment]
Great, thanks, it works now!
