### ISSUE TITLE
make example returns error

### ISSUE THREAD

**Issue by pktiuk** [23andMe/djdt-flamegraph#11]
I am not able to run example project
```bash
$ make example
virtualenv --python=python example/env
created virtual environment CPython3.8.10.final.0-64 in 174ms
  creator CPython3Posix(dest=/tmp/tmp/djdt-flamegraph/example/env, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, pkg_resources=latest, via=copy, app_data_dir=/home/pawel/.local/share/virtualenv/seed-app-data/v1.0.1.debian.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
example/env/bin/pip install -r example/requirements.txt
Collecting django
  Using cached Django-4.0-py3-none-any.whl (8.0 MB)
Collecting django-debug-toolbar
  Using cached django_debug_toolbar-3.2.2-py3-none-any.whl (200 kB)
Collecting sqlparse>=0.2.2
  Using cached sqlparse-0.4.2-py3-none-any.whl (42 kB)
Collecting asgiref<4,>=3.4.1
  Using cached asgiref-3.4.1-py3-none-any.whl (25 kB)
Collecting backports.zoneinfo; python_version < "3.9"
  Using cached backports.zoneinfo-0.2.1-cp38-cp38-manylinux1_x86_64.whl (74 kB)
Installing collected packages: sqlparse, asgiref, backports.zoneinfo, django, django-debug-toolbar
Successfully installed asgiref-3.4.1 backports.zoneinfo-0.2.1 django-4.0 django-debug-toolbar-3.2.2 sqlparse-0.4.2
example/env/bin/pip install -e `pwd`
Obtaining file:///tmp/tmp/djdt-flamegraph
Installing collected packages: djdt-flamegraph
  Running setup.py develop for djdt-flamegraph
Successfully installed djdt-flamegraph
example/env/bin/python example/manage.py migrate
Traceback (most recent call last):
  File "example/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/tmp/tmp/djdt-flamegraph/example/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/tmp/tmp/djdt-flamegraph/example/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/tmp/tmp/djdt-flamegraph/example/env/lib/python3.8/site-packages/django/core/management/base.py", line 373, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/tmp/tmp/djdt-flamegraph/example/env/lib/python3.8/site-packages/django/core/management/base.py", line 417, in execute
    output = self.handle(*args, **options)
  File "/tmp/tmp/djdt-flamegraph/example/env/lib/python3.8/site-packages/django/core/management/base.py", line 90, in wrapped
    res = handle_func(*args, **kwargs)
  File "/tmp/tmp/djdt-flamegraph/example/env/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/tmp/tmp/djdt-flamegraph/example/env/lib/python3.8/site-packages/django/core/management/base.py", line 438, in check
    all_issues = checks.run_checks(
  File "/tmp/tmp/djdt-flamegraph/example/env/lib/python3.8/site-packages/django/core/checks/registry.py", line 77, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/tmp/tmp/djdt-flamegraph/example/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/tmp/tmp/djdt-flamegraph/example/env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/tmp/tmp/djdt-flamegraph/example/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 446, in check
    for pattern in self.url_patterns:
  File "/tmp/tmp/djdt-flamegraph/example/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tmp/tmp/djdt-flamegraph/example/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 632, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/tmp/tmp/djdt-flamegraph/example/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tmp/tmp/djdt-flamegraph/example/env/lib/python3.8/site-packages/django/urls/resolvers.py", line 625, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmp/djdt-flamegraph/example/mysite/urls.py", line 16, in <module>
    from django.conf.urls import url, include, patterns
ImportError: cannot import name 'url' from 'django.conf.urls' (/tmp/tmp/djdt-flamegraph/example/env/lib/python3.8/site-packages/django/conf/urls/__init__.py)
make: *** [Makefile:21: example/env] Błąd 1

```

**Comment by blopker** [comment]
Hey @pktiuk, thanks for trying this out, but this should have been archived a while a go. Sorry for the inconvenience!
